@startuml scanner

state Scan {
    [*] --> MotorMovement
    
    state CurrentAngle <<choice>>
    MotorMovement --> CurrentAngle

    CurrentAngle --> Measure : [limit not reached]
    CurrentAngle --> [*] : [limit reached]

    Measure --> LedBlink : object detected
    Measure --> MotorMovement

    LedBlink --> MotorMovement
}

@enduml